export const FORMATION_CREATE_REQUEST = 'FORMATION_CREATE_REQUEST'
export const FORMATION_CREATE_SUCCESS = 'FORMATION_CREATE_SUCCESS'
export const FORMATION_CREATE_FAIL = 'FORMATION_CREATE_FAIL'
export const FORMATION_CREATE_RESET = 'FORMATION_CREATE_RESET'


export const FORMATION_DELETE_REQUEST = 'FORMATION_DELETE_REQUEST'
export const FORMATION_DELETE_SUCCESS = 'FORMATION_DELETE_SUCCESS'
export const FORMATION_DELETE_FAIL = 'FORMATION_DELETE_FAIL'



export const FORMATION_LIST_REQUEST = 'FORMATION_LIST_REQUEST'
export const FORMATION_LIST_SUCCESS = 'FORMATION_LIST_SUCCESS'
export const FORMATION_LIST_FAIL = 'FORMATION_LIST_FAIL'



export const FORMATION_DETAILS_REQUEST = 'FORMATION_DETAILS_REQUEST'
export const FORMATION_DETAILS_SUCCESS = 'FORMATION_DETAILS_SUCCESS'
export const FORMATION_DETAILS_FAIL = 'FORMATION_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const FORMATION_UPDATE_REQUEST = 'FORMATION_UPDATE_REQUEST'
export const FORMATION_UPDATE_SUCCESS = 'FORMATION_UPDATE_SUCCESS'
export const FORMATION_UPDATE_FAIL = 'FORMATION_UPDATE_FAIL'
export const FORMATION_UPDATE_RESET = 'FORMATION_UPDATE_RESET'


export const ENVOYER_MAIL_SUCCESS = 'ENVOYER_MAIL_SUCCESS'
export const ENVOYER_MAIL_FAILURE = 'ENVOYER_MAIL_FAILURE'
export const ENVOYER_MAIL_REQUEST = 'ENVOYER_MAIL_REQUEST'

export const ENVOYER_MAIL2_SUCCESS = 'ENVOYER_MAIL2_SUCCESS'
export const ENVOYER_MAIL2_FAILURE = 'ENVOYER_MAIL2_FAILURE'
export const ENVOYER_MAIL2_REQUEST = 'ENVOYER_MAIL2_REQUEST'

export const ENVOYER_MAIL3_SUCCESS = 'ENVOYER_MAIL3_SUCCESS'
export const ENVOYER_MAIL3_FAILURE = 'ENVOYER_MAIL3_FAILURE'
export const ENVOYER_MAIL3_REQUEST = 'ENVOYER_MAIL3_REQUEST'


export const ENVOYER_MAIL4_SUCCESS = 'ENVOYER_MAIL4_SUCCESS'
export const ENVOYER_MAIL4_FAILURE = 'ENVOYER_MAIL4_FAILURE'
export const ENVOYER_MAIL4_REQUEST = 'ENVOYER_MAIL4_REQUEST'


export const ENVOYER_MAIL5_SUCCESS = 'ENVOYER_MAIL5_SUCCESS'
export const ENVOYER_MAIL5_FAILURE = 'ENVOYER_MAIL5_FAILURE'
export const ENVOYER_MAIL5_REQUEST = 'ENVOYER_MAIL5_REQUEST'